### ISSUE TITLE
ToDo for v1.0.0

### ISSUE THREAD

**Issue by koluku** [koluku/s3s#22]
## compatibility with s3select

- [x] csv support
- [x] limit option
- [ ] verbose option
- [x] count option
- [ ] with_filename option
- [ ] aws profile option
- [x] max_retries option

## fail-safe

- [ ] stop if s3s will scan 10gb over

## fast

- [x] more parallel processing
- [ ] use `sync.pool` ?
- [x] print with once flush

## useful

- [x] dry-run option
